using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using MelonLoader;
using UnityEngine;

using Bnfour.MoeJigsawMods.PieceFreeze.Data;

namespace Bnfour.MoeJigsawMods.PieceFreeze.Utilities;

/// <summary>
/// Stores which pieces were frozen per puzzle.
/// Only exposes data for the currently active puzzle.
/// </summary>
internal class DataStorage
{
    // TODO consider moving file ops somewhere else
    private const string Filename = "pieces.frz";
    private readonly string FullFilePath = Path.Combine(Application.dataPath, Filename);

    private const string Header = "[Bnfour_PieceFreeze_SaveData] Do not edit this file manually! Pretty please? Things might break if you miss a piece or two.";

    private readonly Regex KeyRegex = new("AM-[0-9]{2}_[0-9]{4}-[0-9]{4}");
    private readonly Regex PieceNameRegex = new("piece_[0-9]{2}_[0-9]{2}");

    private Dictionary<string, HashSet<string>> _backend;

    private string CurrentKey
    {
        get
        {
            var key = GameManager.Instance.puzzleMainInfo.databaseId;

            if (string.IsNullOrEmpty(key))
            {
                throw new ApplicationException("No database id set yet. Is the puzzle loaded?");
            }

            return key;
        }
    }

    internal HashSet<string> Current
    {
        get
        {
            if (!_backend.ContainsKey(CurrentKey))
            {
                _backend[CurrentKey] = new();
            }
            return _backend[CurrentKey];
        }
    }

    internal void ResetCurrent()
    {
        if (_backend.ContainsKey(CurrentKey))
        {
            _backend.Remove(CurrentKey);
        }
    }

    internal void Save()
    {
        // TODO consider doing nothing if the state did not change during the game session
        // (kinda rare outside of just opening/closing the game)

        if (_backend.Count > 0)
        {
            File.WriteAllText(FullFilePath, Serialize());
        }
        else if (File.Exists(FullFilePath))
        {
            File.Delete(FullFilePath);
        }
    }

    internal void Load()
    {
        if (File.Exists(FullFilePath))
        {
            try
            {
                _backend = Deserialize(File.ReadAllText(FullFilePath));
            }
            catch (Exception e)
            {
                Melon<PieceFreezeMod>.Logger.Error($"Unable to load save state{(e is DataLoadException dle ? $": {dle.Message}" : "")}! The file will be overwritten on exit.");
                _backend = new();
            }
        }
        else
        {
            _backend = new();
        }
    }


    // so yeah, Newtonsoft.Json is unable to load System.Runtime.Serialization,
    // here we go with a custom "format"
    
    // every non-empty string except the header is an entry: key|piece_XX_YY,...,piece_WW_ZZ
    
    private string Serialize()
    {
        var sb = new StringBuilder(Header + '\n');
        foreach (var kvp in _backend)
        {
            if (kvp.Value.Count > 0)
            {
                sb.Append($"{kvp.Key}|{string.Join(",", [.. kvp.Value])}\n");
            }
        }
        return sb.ToString();
    }

    private Dictionary<string, HashSet<string>> Deserialize(string input)
    {
        Dictionary<string, HashSet<string>> result = new();

        var lines = input.Split('\n');
        var header = lines.First();
        var dataLines = lines.Skip(1);

        if (header != Header)
        {
            throw new DataLoadException("missing file header");
        }

        foreach (var line in dataLines)
        {
            if (string.IsNullOrEmpty(line))
            {
                continue;
            }

            var keySplit = line.Split('|');
            if (keySplit.Length != 2)
            {
                throw new DataLoadException("unable to separate key and data");
            }

            var key = keySplit.First();
            if (string.IsNullOrEmpty(key) || !KeyRegex.IsMatch(key))
            {
                throw new DataLoadException($"invalid puzzle key \"{key}\"");
            }
            result[key] = new();

            var setContents = keySplit.Last().Split(',');
            foreach (var s in setContents)
            {
                if (!string.IsNullOrEmpty(s) && PieceNameRegex.IsMatch(s))
                {
                    result[key].Add(s);
                }
                else
                {
                    throw new DataLoadException($"invalid piece name \"{s}\"");
                }
            }
        }

        return result;
    }
}
