using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;

namespace Bnfour.MoeJigsawMods.PieceFreeze.Utilities;

/// <summary>
/// Stores which pieces were frozen per puzzle.
/// Only exposes data for the currently active puzzle.
/// </summary>
internal class DataStorage
{
    private const string Filename = "pieces.frz";
    private readonly string FullFilePath = Path.Combine(Application.dataPath, Filename);

    private const string Header = "[Bnfour_PieceFreeze_SaveData] Do not edit this file manually! Pretty please? Things might break if you miss a piece or two.";

    private Dictionary<string, HashSet<string>> _backend;

    private string CurrentKey
    {
        get
        {
            var key = GameManager.Instance.puzzleMainInfo.databaseId;

            if (string.IsNullOrEmpty(key))
            {
                throw new ApplicationException("No database id set yet. Is the puzzle loaded?");
            }

            return key;
        }
    }

    internal HashSet<string> Current
    {
        get
        {
            if (!_backend.ContainsKey(CurrentKey))
            {
                _backend[CurrentKey] = new();
            }
            return _backend[CurrentKey];
        }
    }

    // TODO find where to plug it on puzzle reset
    internal void ResetCurrent()
    {
        _backend.Remove(CurrentKey);
    }

    internal void Save()
    {
        // TODO try section?
        File.WriteAllText(FullFilePath, Serialize());
    }

    internal void Load()
    {
        if (File.Exists(FullFilePath))
        {
            // TODO try section
            _backend = Deserialize(File.ReadAllText(FullFilePath));
        }
        else
        {
            _backend = new();
        }
    }


    // so yeah, Newtonsoft.Json is unable to load System.Runtime.Serialization,
    // here we go with a custom "format"
    
    // every non-empty string except the header is an entry: key|piece_XX_YY,...,piece_WW_ZZ
    
    // very work in progress
    private string Serialize()
    {
        var sb = new StringBuilder(Header + '\n');
        foreach (var kvp in _backend)
        {
            if (kvp.Value.Count > 0)
            {
                sb.Append($"{kvp.Key}|{string.Join(",", [.. kvp.Value])}\n");
            }
        }
        return sb.ToString();
    }

    private Dictionary<string, HashSet<string>> Deserialize(string input)
    {
        // TODO validate string values?
        Dictionary<string, HashSet<string>> result = new();

        var lines = input.Split('\n');
        var header = lines.First();
        var dataLines = lines.Skip(1);

        if (header != Header)
        {
            throw new ArgumentException("Missing file header");
        }

        foreach (var line in dataLines)
        {
            if (string.IsNullOrEmpty(line))
            {
                continue;
            }

            var keySplit = line.Split('|');
            if (keySplit.Length != 2)
            {
                throw new ArgumentException("Unable to separate key and data");
            }

            var key = keySplit.First();
            if (string.IsNullOrEmpty(key))
            {
                throw new ArgumentException("Empty key");
            }
            result[key] = new();

            var setContents = keySplit.Last().Split(',');
            foreach (var s in setContents)
            {
                if (!string.IsNullOrEmpty(s))
                {
                    result[key].Add(s);
                }
            }
        }

        return result;
    }
}
