# see my other repos for details, this is a simplified workflow:
# there are no tests nor external libraries to include

name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Fetch tags
      run: git fetch --tags
    - name: Download external dependencies
      env:
        PASS: ${{ secrets.DOWNLOAD_PASSWORD }}
        URL: ${{ secrets.DOWNLOAD_URL }}
      run: curl -u "runner:$PASS" "$URL" --output references.zip
    - name: Unpack external dependencies
      run: unzip references.zip -d references/
    - name: Restore NuGet dependencies (not that it's required)
      run: dotnet restore
    - name: Release build (out of the gate)
      run: dotnet build -c Release --no-restore release.slnf
    - name: Create folder structure
      run: mkdir --verbose release
    - name: Add text assets
      run: bash build/text-assets.sh
    - name: Add mod DLLs
      run: bash build/mod-dlls.sh
    - name: Show the resulting asset structure
      run: tree -sh --dirsfirst release/
    - name: Show and store DLL checksums
      run: bash build/checksums.sh
    - name: Figure out the release version and archive name
      run: bash build/get-version.sh
    - name: Zip the archive
      run: bash build/zip.sh
    - name: Draft the release notes
      run: bash build/notes.sh
    - name: Draft the actual release in the repo
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "v$new_version" "$filename" --draft --title "v$new_version — tl;dr" --notes-file notes --fail-on-no-commits
